<template><div>
  <el-form :inline="true" :model="query"><el-form-item label="课程ID"><el-input v-model="query.courseId"/></el-form-item><el-form-item label="状态"><el-select v-model="query.status" clearable style="width:120px"><el-option :value="0" label="未发布"/><el-option :value="1" label="进行中"/><el-option :value="2" label="已结束"/></el-select></el-form-item><el-form-item><el-button type="primary" @click="load">查询</el-button><el-button type="success" @click="openAdd">新增考试</el-button></el-form-item></el-form>
  <el-table :data="tableData" border><el-table-column prop="id" label="ID" width="80"/><el-table-column prop="title" label="标题"/><el-table-column prop="duration" label="时长"/><el-table-column prop="status" label="状态"/><el-table-column label="操作"><template #default="s"><el-button link type="primary" @click="openEdit(s.row)">编辑</el-button><el-button link @click="publish(s.row.id)">发布</el-button><el-button link @click="gen(s.row.id)">自动组卷</el-button><el-button link type="danger" @click="del(s.row.id)">删除</el-button></template></el-table-column></el-table>
  <el-pagination class="mt-12" background layout="total, prev, pager, next" :total="total" v-model:current-page="query.pageNum" v-model:page-size="query.pageSize" @current-change="load"/>
  <el-dialog v-model="visible" :title="title"><el-form ref="formRef" :model="form" :rules="rules" label-width="100px"><el-form-item label="课程ID" prop="courseId"><el-input v-model="form.courseId"/></el-form-item><el-form-item label="标题" prop="title"><el-input v-model="form.title"/></el-form-item><el-form-item label="时长" prop="duration"><el-input-number v-model="form.duration" :min="1"/></el-form-item><el-form-item label="总分" prop="totalScore"><el-input-number v-model="form.totalScore" :min="1"/></el-form-item><el-form-item label="及格分" prop="passScore"><el-input-number v-model="form.passScore" :min="1"/></el-form-item><el-form-item label="开始时间" prop="startTime"><el-date-picker v-model="form.startTime" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss"/></el-form-item><el-form-item label="结束时间" prop="endTime"><el-date-picker v-model="form.endTime" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss"/></el-form-item></el-form><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" @click="submit">保存</el-button></template></el-dialog>
</div></template>
<script setup>
import { reactive, ref } from 'vue'; import { ElMessage, ElMessageBox } from 'element-plus'; import { getExamList, addExam, updateExam, deleteExam, publishExam, autoGenerateExam } from '@/api/exam';
const query=reactive({pageNum:1,pageSize:10,courseId:'',status:undefined}); const tableData=ref([]); const total=ref(0); const visible=ref(false); const title=ref('新增考试'); const formRef=ref();
const form=reactive({id:null,courseId:'',title:'',duration:60,totalScore:100,passScore:60,startTime:'',endTime:''}); const rules={courseId:[{required:true,message:'必填',trigger:'blur'}],title:[{required:true,message:'必填',trigger:'blur'}]};
const load=async()=>{const {data}=await getExamList(query); tableData.value=data.data.list; total.value=data.data.total;};
const openAdd=()=>{title.value='新增考试';Object.assign(form,{id:null,courseId:'',title:'',duration:60,totalScore:100,passScore:60,startTime:'',endTime:''});visible.value=true;};
const openEdit=(r)=>{title.value='编辑考试';Object.assign(form,r);visible.value=true;};
const submit=async()=>{await formRef.value.validate(); if(form.id) await updateExam(form); else await addExam(form); ElMessage.success('保存成功'); visible.value=false; load();};
const del=async(id)=>{await ElMessageBox.confirm('确认删除?','提示'); await deleteExam(id); ElMessage.success('删除成功'); load();};
const publish=async(id)=>{await publishExam(id); ElMessage.success('发布成功'); load();};
const gen=async(id)=>{await autoGenerateExam({examId:id}); ElMessage.success('组卷完成');};
</script>
