<template><div>
  <el-form :inline="true" :model="query"><el-form-item label="课程ID"><el-input v-model="query.courseId"/></el-form-item><el-form-item label="题型"><el-select v-model="query.type" clearable style="width:120px"><el-option :value="1" label="单选"/><el-option :value="2" label="判断"/><el-option :value="3" label="简答"/></el-select></el-form-item><el-form-item><el-button type="primary" @click="load">查询</el-button><el-button type="success" @click="openAdd">新增</el-button></el-form-item></el-form>
  <el-table :data="tableData" border><el-table-column prop="id" label="ID" width="80"/><el-table-column prop="courseId" label="课程ID"/><el-table-column prop="type" label="题型"/><el-table-column prop="content" label="题干"/><el-table-column prop="difficulty" label="难度"/><el-table-column label="操作"><template #default="s"><el-button link type="primary" @click="openEdit(s.row)">编辑</el-button><el-button link type="danger" @click="del(s.row.id)">删除</el-button></template></el-table-column></el-table>
  <el-pagination class="mt-12" background layout="total, prev, pager, next" :total="total" v-model:current-page="query.pageNum" v-model:page-size="query.pageSize" @current-change="load"/>
  <el-dialog v-model="visible" :title="title"><el-form ref="formRef" :model="form" :rules="rules" label-width="80px"><el-form-item label="课程ID" prop="courseId"><el-input v-model="form.courseId"/></el-form-item><el-form-item label="题型" prop="type"><el-select v-model="form.type"><el-option :value="1" label="单选"/><el-option :value="2" label="判断"/><el-option :value="3" label="简答"/></el-select></el-form-item><el-form-item label="题干" prop="content"><el-input type="textarea" v-model="form.content"/></el-form-item><el-form-item label="选项JSON"><el-input type="textarea" v-model="form.options"/></el-form-item><el-form-item label="答案" prop="answer"><el-input v-model="form.answer"/></el-form-item><el-form-item label="难度" prop="difficulty"><el-input-number v-model="form.difficulty" :min="1" :max="5"/></el-form-item></el-form><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" @click="submit">保存</el-button></template></el-dialog>
</div></template>
<script setup>
import { reactive, ref } from 'vue'; import { ElMessage, ElMessageBox } from 'element-plus'; import { getQuestionList, addQuestion, updateQuestion, deleteQuestion } from '@/api/question';
const query=reactive({pageNum:1,pageSize:10,courseId:'',type:undefined}); const tableData=ref([]); const total=ref(0); const visible=ref(false); const title=ref('新增题目'); const formRef=ref();
const form=reactive({id:null,courseId:'',type:1,content:'',options:'[]',answer:'',difficulty:3}); const rules={courseId:[{required:true,message:'必填',trigger:'blur'}],content:[{required:true,message:'必填',trigger:'blur'}],answer:[{required:true,message:'必填',trigger:'blur'}]};
const load=async()=>{const {data}=await getQuestionList(query); tableData.value=data.data.list; total.value=data.data.total;};
const openAdd=()=>{title.value='新增题目';Object.assign(form,{id:null,courseId:'',type:1,content:'',options:'[]',answer:'',difficulty:3});visible.value=true;};
const openEdit=(r)=>{title.value='编辑题目';Object.assign(form,r);visible.value=true;};
const submit=async()=>{await formRef.value.validate(); if(form.id) await updateQuestion(form); else await addQuestion(form); ElMessage.success('保存成功'); visible.value=false; load();};
const del=async(id)=>{await ElMessageBox.confirm('确认删除?','提示'); await deleteQuestion(id); ElMessage.success('删除成功'); load();};
</script>
