CREATE TABLE IF NOT EXISTS course_category (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(128) NOT NULL COMMENT '分类名称',
  sort INT NOT NULL DEFAULT 0 COMMENT '排序',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  KEY idx_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='课程分类';

CREATE TABLE IF NOT EXISTS lecturer (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(128) NOT NULL COMMENT '讲师姓名',
  title VARCHAR(128) DEFAULT NULL COMMENT '讲师头衔',
  avatar_url VARCHAR(255) DEFAULT NULL COMMENT '头像地址',
  bio TEXT COMMENT '简介',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  KEY idx_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='讲师表';

CREATE TABLE IF NOT EXISTS course (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(200) NOT NULL COMMENT '课程名称',
  category_id BIGINT DEFAULT NULL COMMENT '分类ID',
  lecturer_id BIGINT DEFAULT NULL COMMENT '讲师ID',
  description TEXT COMMENT '课程描述',
  cover_url VARCHAR(255) DEFAULT NULL COMMENT '封面URL',
  status TINYINT NOT NULL DEFAULT 0 COMMENT '状态 0草稿 1上架',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  KEY idx_name (name),
  KEY idx_category_id (category_id),
  KEY idx_lecturer_id (lecturer_id),
  KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='课程表';

CREATE TABLE IF NOT EXISTS course_material (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  course_id BIGINT NOT NULL COMMENT '课程ID',
  file_name VARCHAR(255) NOT NULL COMMENT '文件名',
  file_url VARCHAR(255) NOT NULL COMMENT '文件地址',
  file_type VARCHAR(20) NOT NULL COMMENT '文件类型',
  size BIGINT NOT NULL COMMENT '文件大小(字节)',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  KEY idx_course_id (course_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='课件表';

CREATE TABLE IF NOT EXISTS learning_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  plan_id BIGINT DEFAULT NULL,
  course_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  study_date DATE DEFAULT NULL,
  study_minutes INT DEFAULT 0,
  progress_percent DECIMAL(5,2) DEFAULT 0.00,
  completion_status TINYINT DEFAULT 0,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  KEY idx_course_id (course_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='学习记录表';
