CREATE TABLE IF NOT EXISTS learning_progress (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  course_id BIGINT NOT NULL,
  progress INT NOT NULL DEFAULT 0 COMMENT '0-100',
  last_learn_time DATETIME DEFAULT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  KEY idx_user_id (user_id),
  KEY idx_course_id (course_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='学习进度表';

CREATE TABLE IF NOT EXISTS learning_reminder (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  course_id BIGINT NOT NULL,
  reminder_type TINYINT NOT NULL COMMENT '1未学习 2进度落后 3临近截止',
  content VARCHAR(1000) NOT NULL,
  reminder_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status TINYINT NOT NULL DEFAULT 0 COMMENT '0未读 1已读',
  deleted TINYINT NOT NULL DEFAULT 0,
  KEY idx_user_id (user_id),
  KEY idx_type (reminder_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='学习提醒表';

CREATE TABLE IF NOT EXISTS learning_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  course_id BIGINT NOT NULL,
  duration INT NOT NULL COMMENT '学习总时长(分钟)',
  finish_time DATETIME DEFAULT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  KEY idx_user_id (user_id),
  KEY idx_course_id (course_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='学习档案表';

CREATE TABLE IF NOT EXISTS learning_my_task_cache (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  plan_id BIGINT NOT NULL,
  course_id BIGINT NOT NULL,
  progress INT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 0,
  deadline DATETIME DEFAULT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='我的学习任务缓存(可选)';
