CREATE TABLE sys_user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(64) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  real_name VARCHAR(64) NOT NULL,
  email VARCHAR(128),
  phone VARCHAR(32),
  dept_id BIGINT,
  status TINYINT NOT NULL DEFAULT 1,
  last_login_time DATETIME,
  created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE sys_role (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  role_code VARCHAR(64) NOT NULL UNIQUE,
  role_name VARCHAR(64) NOT NULL,
  data_scope VARCHAR(32) DEFAULT 'SELF',
  status TINYINT NOT NULL DEFAULT 1
);

CREATE TABLE sys_dept (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  parent_id BIGINT DEFAULT 0,
  dept_code VARCHAR(64) NOT NULL UNIQUE,
  dept_name VARCHAR(128) NOT NULL,
  leader_id BIGINT,
  status TINYINT NOT NULL DEFAULT 1
);

CREATE TABLE t_course (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  code VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(128) NOT NULL,
  category VARCHAR(64),
  lecturer_id BIGINT,
  hours INT NOT NULL DEFAULT 0,
  difficulty VARCHAR(16),
  status VARCHAR(16) NOT NULL DEFAULT 'DRAFT'
);

CREATE TABLE t_training_plan (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  plan_no VARCHAR(64) NOT NULL UNIQUE,
  plan_name VARCHAR(128) NOT NULL,
  year INT NOT NULL,
  quarter INT,
  owner_id BIGINT,
  start_date DATE,
  end_date DATE,
  status VARCHAR(16) NOT NULL DEFAULT 'DRAFT'
);

CREATE TABLE t_learning_task (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  course_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  plan_id BIGINT,
  progress DECIMAL(5,2) NOT NULL DEFAULT 0,
  status VARCHAR(16) NOT NULL DEFAULT 'NOT_STARTED'
);

CREATE TABLE t_exam (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  exam_no VARCHAR(64) NOT NULL UNIQUE,
  exam_name VARCHAR(128) NOT NULL,
  course_id BIGINT NOT NULL,
  duration INT NOT NULL,
  total_score DECIMAL(6,2) NOT NULL,
  pass_score DECIMAL(6,2) NOT NULL,
  start_time DATETIME,
  end_time DATETIME,
  status VARCHAR(16) NOT NULL DEFAULT 'DRAFT'
);

CREATE TABLE t_retake_apply (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  exam_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  reason VARCHAR(500),
  apply_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  approval_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
  approver_id BIGINT
);
